List<Map<String, dynamic>> fiftyTitles = [
  {'title': '1. Tsa Koj Txhais Tes Qhuas Vajtswv', 'pageNumber': 1},
  {'title': '2. Thaum Peb Los Pehawm', 'pageNumber': 1},
  {'title': '3. Kuv Los Cuag Tus Tswv', 'pageNumber': 2},
  {'title': '4. Cia Li Muaj Kev Ntseeg Hauv Vajtswv', 'pageNumber': 2},
  {'title': '5. Thov Ntxuav Kuv', 'pageNumber': 3},
  {'title': '6. Koj Nrog Nraim', 'pageNumber': 3},
  {'title': '7. Vajtswv Yog Dej Cawv Txoj Sia', 'pageNumber': 4},
  {'title': '8. Nov Yog Peb Cov Lus Thov', 'pageNumber': 4},
  {'title': '9. Koj Yog Kev Kaj', 'pageNumber': 5},
  {'title': '10. Nov Yog Kuv Lubsiab Ntshaw', 'pageNumber': 6},
  {'title': '11. Koj Lub Npe Qab Zib Li Zib Ntab', 'pageNumber': 6},
  {'title': '12. Koj Yog Lub Zog', 'pageNumber': 7},
  {'title': '13. Leej Twg Yuav Piv Tau', 'pageNumber': 7},
  {'title': '14. Txhua Lub Sijhawm', 'pageNumber': 8},
  {'title': '15. Txoj Sia Nyob Hauv Vajtswv', 'pageNumber': 9},
  {'title': '16. Peb Zoo Lub Saib', 'pageNumber': 9},
  {'title': '17. Cia Li Hu Nkauj Qhuas Vajtswv', 'pageNumber': 10},
  {'title': '18. Tus Dej Ntws Hauv Lub Saib', 'pageNumber': 11},
  {'title': '19. Peb Txhua Tus Zoo Siab', 'pageNumber': 11},
  {'title': '20. Los Nov Yog Sijhawm', 'pageNumber': 12},
  {'title': '21. Qhib Kuv Lub Qhov Muag Siab', 'pageNumber': 12},
  {'title': '22. Peb Txhos Caug Peb Txo Cwj Chim', 'pageNumber': 13},
  {'title': '23. Coj Kuv Los Cuag Koj', 'pageNumber': 13},
  {'title': '24. Hloov Kuv Siab Tus Tswv', 'pageNumber': 13},
  {'title': '25. Kuv Mus Rau Qhov Chaw Ua Dawb Huv', 'pageNumber': 14},
  {'title': '26. Hu Ib Zaj Nkauj Tshiab Qhuas Tus Tswv', 'pageNumber': 14},
  {'title': '27. Kuv Paub Koj Tseem Muaj Sia Nyob', 'pageNumber': 15},
  {'title': '28. Leej Twg Thiaj Yuav Tsim Nyog Pe Hawm Koj', 'pageNumber': 15},
  {'title': '29. Vajtswv Koj Yog Kuv Tus Tswv', 'pageNumber': 16},
  {'title': '30. Txhua Lub Suab Qhuas Tus Tswv', 'pageNumber': 17},
  {'title': '31. Kuv Paub Koj Nyob Ntawm No', 'pageNumber': 17},
  {'title': '32. Thov Koj Los Kav Kuv Lub Neej Dua', 'pageNumber': 18},
  {'title': '33. Peb Tuaj No Tuaj Txhawb Nqa Koj', 'pageNumber': 19},
  {'title': '34. Yuav Tsum Niaj Hnub Zoo Siab', 'pageNumber': 20},
  {'title': '35. Peb Yuav Txhawb Nqa Koj', 'pageNumber': 20},
  {'title': '36. Thov Tus Tswv Koj Puag Kuv Cia', 'pageNumber': 21},
  {'title': '37. Peb Yuav Pehawm Koj', 'pageNumber': 21},
  {'title': '38. Vajtswv Txoj Kev Hlub Kuv', 'pageNumber': 22},
  {'title': '39. Kuv Taij Thov Txog Tswv Yexus', 'pageNumber': 23},
  {'title': '40. Nrhiav Tus Tswv', 'pageNumber': 23},
  {'title': '41. Cia Vajtswv Coj Hauv Kev', 'pageNumber': 24},
  {'title': '42. Ceeb Tsheej Ntiaj Teb Hu Nkauj Qhuas Koj', 'pageNumber': 25},
  {'title': '43. Ua Tsaug Rau Saum Khaub Lig Ntoo', 'pageNumber': 25},
  {'title': '44. Vajtswv Kev Hlub Tsis Hloov', 'pageNumber': 26},
  {'title': '45. Qhuas Vajtswv Lub Npe', 'pageNumber': 27},
  {'title': '46. Kuv Tsis Muaj Leej Twg Zoo Tshaj Vaj LeejTxiv', 'pageNumber': 27},
  {'title': '47. Koj Cawm Kuv Dim', 'pageNumber': 28},
  {'title': '48. Halelusyas Txhawb Nqa Vajtswv', 'pageNumber': 28},
  {'title': '49. Tus Tswv Yog Tus Cawm Kuv Dim', 'pageNumber': 29},
  {'title': '50. Hlub Koj Ib Txhis', 'pageNumber': 29}
];

List<Map<String, dynamic>> newHundredTitles = [
  {'title': '1. Ntiajteb Qaumntuj Qhia Txog Vajtswv', 'pageNumber': 1},
  {'title': '2. Sij Hawm No', 'pageNumber': 1},
  {'title': '3. Vajtswv Tus Ncaj Ncees', 'pageNumber': 2},
  {'title': '4. Vajtswv Tus Ib Txwm Muaj Nyob', 'pageNumber': 2},
  {'title': '5. Tswv Yexus Koj Dawb Huv', 'pageNumber': 3},
  {'title': '6. Kuv Qhuas Vajtswv Kev Hlub', 'pageNumber': 4},
  {'title': '7. Kev Kaj Siab Hauv Kuv', 'pageNumber': 4},
  {'title': '8. Tswv Yexus Lub Hwj Chim', 'pageNumber': 5},
  {'title': '9. Kuv Lub Siab Txhawb Nqa Tswv Yexus', 'pageNumber': 5},
  {'title': '10. Txhawb Nqa Vajntxwv Koj', 'pageNumber': 6},
  {'title': '11. Thoob Plaws Ntiajteb Zoo Siab', 'pageNumber': 7},
  {'title': '12. Vajtswv Nyob Nrog Peb', 'pageNumber': 7},
  {'title': '13. Saum Ceeb Tsheej', 'pageNumber': 8},
  {'title': '14. Rau Siab Ntso Thov Vajtswv', 'pageNumber': 9},
  {'title': '15. Kom Tus Tswv Lub Npe Tau Kev Txhawb Nqa', 'pageNumber': 9},
  {'title': '16. Muab Tag Nrho Rau Koj', 'pageNumber': 10},
  {'title': '17. Txhua Zaus Kuv Thov Vajtswv', 'pageNumber': 10},
  {'title': '18. Kuv Lub Siab Txhawb Nqa Tswv Yexus', 'pageNumber': 11},
  {'title': '19. Kuv Tau Ntsib Tus Tswv', 'pageNumber': 11},
  {'title': '20. Vajtswv Koj Yog Kuv Lub Chaw Nraim', 'pageNumber': 12},
  {'title': '21. Peb Zoo Siab Los Pe Hawm Vajtswv', 'pageNumber': 12},
  {'title': '22. Vajtswv Txoj Kev Hlub', 'pageNumber': 13},
  {'title': '23. Thov Caw Vaj Ntsujplig', 'pageNumber': 13},
  {'title': '24. Tsis Muaj Leej Twg Dua Ntawm Koj', 'pageNumber': 14},
  {'title': '25. Thov Txhawb Nqa Ua Koj Tsaug Vajtswv', 'pageNumber': 14},
  {'title': '26. Peb Yuav Coj Tib Neeg Los Rau Kev Txhawb Nqa', 'pageNumber': 15},
  {'title': '27. Hais Lo Lus Hlub', 'pageNumber': 15},
  {'title': '28. Txhawb Nqa Tus Uas Dawb Huv', 'pageNumber': 16},
  {'title': '29. Tib Yam Uas Kuv Xav Yog', 'pageNumber': 16},
  {'title': '30. Thov Tsa Kuv', 'pageNumber': 17},
  {'title': '31. Vajtswv Tus Tsim Nyog Txhawb Nqa', 'pageNumber': 17},
  {'title': '32. Kuv Ua Koj Tsaug', 'pageNumber': 18},
  {'title': '33. Kuv Lub Hom Phiaj', 'pageNumber': 18},
  {'title': '34. Tus Muaj Hwj Chim Nws Yog Leej Twg', 'pageNumber': 19},
  {'title': '35. Vajtswv Thov Hloov Kuv Siab Hnub No', 'pageNumber': 19},
  {'title': '36. Lub Hwj Chim', 'pageNumber': 20},
  {'title': '37. Yexus Cov Tub Txib', 'pageNumber': 20},
  {'title': '38. Peb Yuav Hu', 'pageNumber': 21},
  {'title': '39. Peb Tuaj Hu Nkauj Qhuas Vajtswv', 'pageNumber': 21},
  {'title': '40. Koj Yog Tus Tswv Yug Yaj', 'pageNumber': 22},
  {'title': '41. Vajtswv Tus Tsim Nyog Txais Kev Txhawb Nqa', 'pageNumber': 22},
  {'title': '42. Cia Peb Txhawb Nqa', 'pageNumber': 23},
  {'title': '43. Thov Hu Nkauj Txhawb Nqa Vajtswv', 'pageNumber': 23},
  {'title': '44. Kuv Lub Siab', 'pageNumber': 24},
  {'title': '45. Lub Suab Ntawm Kev Zoo Siab', 'pageNumber': 24},
  {'title': '46. Vajtswv Lub Hwj Chim', 'pageNumber': 25},
  {'title': '47. Vajtswv Nyob Nrog Nraim', 'pageNumber': 25},
  {'title': '48. Kuv Ruaj Khov Ntawm Cov Lus Cog', 'pageNumber': 26},
  {'title': '49. Sawv Tsees Npuaj Tes Peb Hu Nkauj', 'pageNumber': 26},
  {'title': '50. Cia Li Pehawm Vajtswv', 'pageNumber': 27},
  {'title': '51. Hoxanas', 'pageNumber': 27},
  {'title': '52. Cia Li Hu Nkauj Txhawb Nqa Vajtswv', 'pageNumber': 28},
  {'title': '53. Kuv Thov Txhos Caug Pehawm', 'pageNumber': 28},
  {'title': '54. Vim Vajtswv Tseem Nyob', 'pageNumber': 29},
  {'title': '55. Kuv Hlub Tus Tswv', 'pageNumber': 29},
  {'title': '56. Haleluyas', 'pageNumber': 30},
  {'title': '57. Peb Tus Vajtswv', 'pageNumber': 30},
  {'title': '58. Nyob Hauv Vajtswv Dejsiab', 'pageNumber': 31},
  {'title': '59. Caw Los Qhuas Nws Lub Npe', 'pageNumber': 31},
  {'title': '60. Kuv Yuav Hlub Thiab Pehawm', 'pageNumber': 32},
  {'title': '61. Hloov Kuv Lub Siab', 'pageNumber': 32},
  {'title': '62. Yexus Tus Hlub Kuv', 'pageNumber': 33},
  {'title': '63. Thaum Xav Txog Vajtswv Txoj Kev Hlub', 'pageNumber': 33},
  {'title': '64. Tswv Yexus Tau Sawv Hauv Qhov Tuag', 'pageNumber': 34},
  {'title': '65. Tswv Yexus', 'pageNumber': 34},
  {'title': '66. Xav Pom Hmoob Pehawm Vajtswv', 'pageNumber': 35},
  {'title': '67. Kuv Tau Dim Lawm', 'pageNumber': 35},
  {'title': '68. Kuv Yog Hmoob', 'pageNumber': 36},
  {'title': '69. Kuv Hlub Tswv Yexus Tshaj Txhua Txhia Hnub', 'pageNumber': 36},
  {'title': '70. Hloov Pauv Kev Nyuaj Siab', 'pageNumber': 37},
  {'title': '71. Pib Kom Raug', 'pageNumber': 37},
  {'title': '72. Hnub Dhau Hnub', 'pageNumber': 38},
  {'title': '73. Zoo Siab Hnub Christmas', 'pageNumber': 38},
  {'title': '74. Hmo Nyob Ntsiag To', 'pageNumber': 39},
  {'title': '75. Kev Kaj Siab Hnub Christmas', 'pageNumber': 39},
  {'title': '76. Los Hu Nkauj', 'pageNumber': 40},
  {'title': '77. Christmas Sijhawm Kev Hlub', 'pageNumber': 40},
  {'title': '78. Puv Npho Kev Hlub', 'pageNumber': 41},
  {'title': '79. Yuav Muaj Duab Ci Tuaj Rau Hnub Tshiab', 'pageNumber': 41},
  {'title': '80. Ntseeg Hauv Vajtswv', 'pageNumber': 42},
  {'title': '81. Tswv Yexus Yog Tus Pab Koj', 'pageNumber': 42},
  {'title': '82. Ua Koj Tsaug', 'pageNumber': 43},
  {'title': '83. Ntawm Tswv Yehovas Lub Npe', 'pageNumber': 43},
  {'title': '84. Yexus Yog Txoj Kev Kaj', 'pageNumber': 47},
  {'title': '85. Ua Hnub No Kom Zoo Tshaj Qub', 'pageNumber': 48},
  {'title': '86. Leejtwg Yuav mu Qhia', 'pageNumber': 49},
  {'title': '87. Tus Ntseeg Siab', 'pageNumber': 49},
  {'title': '88. Auj Haleluyas', 'pageNumber': 50},
  {'title': '89. Dhau Ntawv Vajtswv', 'pageNumber': 51},
  {'title': '90. Tag kis', 'pageNumber': 51},
  {'title': '91. Nyob Kaj Siab', 'pageNumber': 52},
  {'title': '92. Los Koom Siab Ua Kwv Tij', 'pageNumber': 52},
  {'title': '93. Hloov', 'pageNumber': 53},
  {'title': '94. Peb Yog Ib Tsev Neeg', 'pageNumber': 53},
  {'title': '95. Kuv Yuav Ntshai Tus Dabtsi', 'pageNumber': 54},
  {'title': '96. Txoj Kev Hlub Nyob Ze Koj Txhua Hnub', 'pageNumber': 55},
  {'title': '97. Noj Pw Hais Li Tus Ntseeg', 'pageNumber': 56},
  {'title': '98. Koom Ib Lub Siab', 'pageNumber': 56},
  {'title': '99. Koj Cov Ntshav Ntxuav Kuv Lub Txim', 'pageNumber': 57},
  {'title': '100. Tsis Hnov Qab', 'pageNumber': 58},

];


List<Map<String, dynamic>> oldHundredTitles = [
  {'title': '1. Vajtswv Tus Ntsujplig Dawb Huv', 'pageNumber': 1},
  {'title': '2. Peb Tau Txais Txoj Kev Hlub', 'pageNumber': 2},
  {'title': '3. Tswv Yexus Peb Hlub Koj Kawg', 'pageNumber': 3},
  {'title': '4. Tswv Yexus Thov Koj Hloov Kuv Lub Siab', 'pageNumber': 3},
  {'title': '5. Kuv Txoj Sia Nyob Txog Thaumtwg', 'pageNumber': 4},
  {'title': '6. Kuv Tsa Muag Saib Koj', 'pageNumber': 5},
  {'title': '7. Peb Hlub Vaj Leej Txiv', 'pageNumber': 5},
  {'title': '8. Kuv Hlub Koj Ntawm Vajtswv', 'pageNumber': 6},
  {'title': '9. Vajtswv Yog Kev Hlub', 'pageNumber': 6},
  {'title': '10. Cia Tus Uas Vajtswv Cawm Dim Lawdhais Tias', 'pageNumber': 7},
  {'title': '11. Ntawd Tswv Yexus Lub Npe', 'pageNumber': 7},
  {'title': '12. Peb Yuav Los Hu Nkauj Qhuas', 'pageNumber': 8},
  {'title': '13. Vajtswv Yog Tus Loj Kawg', 'pageNumber': 8},
  {'title': '14. Peb Coj Lub Suab Hu Nkauj Qhuas', 'pageNumber': 9},
  {'title': '15. Hu Hauxana', 'pageNumber': 9},
  {'title': '16. Kev Chivfab Hauv Vajtswv', 'pageNumber': 10},
  {'title': '17. Vajtswv Yog Tus Zoo Kawg', 'pageNumber': 11},
  {'title': '18. Thaum Uas Lub Hnub Ci Ntsa Iab', 'pageNumber': 11},
  {'title': '19. Kuv Yuav Hu Nkauj Qhuas', 'pageNumber': 12},
  {'title': '20. Vajtswv Kuv Hlub Koj', 'pageNumber': 13},
  {'title': '21. Auj Kuv Tus Vajtswv Ntuj', 'pageNumber': 13},
  {'title': '22. Yexus Koj Yog Vajtswv', 'pageNumber': 14},
  {'title': '23. Ua Tsaug Vaj Yexus', 'pageNumber': 14},
  {'title': '24. Hauv Vajtswv Lub Sijhawm', 'pageNumber': 15},
  {'title': '25. Thov Kom Tej Lus Uas Kuv Hais', 'pageNumber': 16},
  {'title': '26. Yuav Tsum Xub Nrhiav Vajtswv Lub Tebchaws', 'pageNumber': 16},
  {'title': '27. Leej Txiv Saub Kuv Ntseeg', 'pageNumber': 17},
  {'title': '28. Kuv Leej Txiv Saub', 'pageNumber': 18},
  {'title': '29. Thaum Tsa Muag Ntsia Yexus', 'pageNumber': 19},
  {'title': '30. Kuv Tus Ntsuj Plig Pheej Ntshaw', 'pageNumber': 20},
  {'title': '31. Yexus Koj Yog Peb Tus Vajtswv', 'pageNumber': 20},
  {'title': '32. Vaj Leej Txiv Kuv Thov Pehawm Koj', 'pageNumber': 21},
  {'title': '33. No Yog Sijhawm', 'pageNumber': 21},
  {'title': '34. Vajtswv Kev Hlub', 'pageNumber': 22},
  {'title': '35. Kuv Lub Neej Niaj Hnub Qhuas Koj', 'pageNumber': 22},
  {'title': '36. Caws Vaj Ntsuj Plig', 'pageNumber': 23},
  {'title': '37. Vaj Ntsuj Pliag Thov Los Kav Kuv Lub Siab', 'pageNumber': 23},
  {'title': '38. Thov Qhib Kuv Lub Qhov Muag', 'pageNumber': 24},
  {'title': '39. Vajtswv Ntuj Thov Kom Kuv Pom Txoj Kev Hlub', 'pageNumber': 24},
  {'title': '40. Kev Kaj Siab Uas Vajtswv Pub', 'pageNumber': 25},
  {'title': '41. Vajtswv Txoj Kev Hlub Zoo Dua Txoj Sia', 'pageNumber': 26},
  {'title': '42. Leej Twg Uas Yuav Mus', 'pageNumber': 26},
  {'title': '43. Salus Saloos', 'pageNumber': 27},
  {'title': '44. Vajtswv Txoj Kev Hlub Ntws Mus', 'pageNumber': 28},
  {'title': '45. Peb Txhua Txhua Tus Cia Li Zoo Siab', 'pageNumber': 28},
  {'title': '46. Cia Li Zoo Siab Ntawm Vajtswv', 'pageNumber': 29},
  {'title': '47. Hauv Kuv Lub Siab Niaj Hnub Kub Lug', 'pageNumber': 29},
  {'title': '48. Ye Hau Va Yi Le', 'pageNumber': 30},
  {'title': '49. Cia Li Sawv Tsees', 'pageNumber': 31},
  {'title': '50. Ntawd Vajtswv Lub Npe', 'pageNumber': 32},
  {'title': '51. Tus Cawm Kuv Yog Vajtswv', 'pageNumber': 32},
  {'title': '52. Tsis Txhob Tshaib', 'pageNumber': 33},
  {'title': '53. Pub Koj Lub Siab', 'pageNumber': 33},
  {'title': '54. Hnub No Yog Hnub', 'pageNumber': 34},
  {'title': '55. Yog Koj Paub Tias Koj Dim Lawm', 'pageNumber': 34},
  {'title': '56. Kuv Tsa Lub Suab', 'pageNumber': 35},
  {'title': '57. Koj Cia Li Tuaj', 'pageNumber': 35},
  {'title': '58. Auj Vajtswv Daws Kuv Txoj Kuv Txhaum', 'pageNumber': 36},
  {'title': '59. Thaum Kuv Lub Neej Los Ntsib Tus Tswv Yexus', 'pageNumber': 37},
  {'title': '60. Kuv Tso Siab Rau Vajtswv Ntuj', 'pageNumber': 38},
  {'title': '61. Vaj Yexus Nws Yog Leej Twg', 'pageNumber': 39},
  {'title': '62. Vajtswv Auj Vajtswv', 'pageNumber': 39},
  {'title': '63. Cia Li Qhuas Vajtswv Ntuj', 'pageNumber': 40},
  {'title': '64. Ua Koj Tsaug Tag Nrho Kuv Lub Siab', 'pageNumber': 40},
  {'title': '65. Tswv Yexus Yog Tus Kov Yeej', 'pageNumber': 41},
  {'title': '66. Tsim Nyog Peb Qhuas', 'pageNumber': 41},
  {'title': '67. Haleluyas', 'pageNumber': 42},
  {'title': '68. Hau Xa Nas', 'pageNumber': 42},
  {'title': '69. Kuv Tus Tswv Vaj Leej Txiv', 'pageNumber': 43},
  {'title': '70. Vajtswv Ntuj Tus Uas Dawb Huv', 'pageNumber': 44},
  {'title': '71. Txhua Zaus Uas Kuv Tsa Suab Thov', 'pageNumber': 44},
  {'title': '72. Thov Qhuas Tswv Yexus', 'pageNumber': 45},
  {'title': '73. Txhawb Nqa Vajtswv', 'pageNumber': 46},
  {'title': '74. Peb Thov Nqa Tes Ua Koj Tsaug', 'pageNumber': 47},
  {'title': '75. Vaj Yexus Peb Zoo Siab Txais Yuav', 'pageNumber': 48},
  {'title': '76. Kuv Tsa Tus Tswv Yexus Lub Npe', 'pageNumber': 48},
  {'title': '77. Tsa Koj Txhais Tes', 'pageNumber': 49},
  {'title': '78. Auj… Peb Tus Tswv Yexus', 'pageNumber': 49},
  {'title': '79. Leej Txiv Saub Vajtswv Ntuj', 'pageNumber': 50},
  {'title': '80. Peb Thov Txhawb Nqa', 'pageNumber': 51},
  {'title': '81. Tus Tswv Yexus', 'pageNumber': 52},
  {'title': '82. Tsis Muaj Ib Yam Piv Tau Koj Txoj Kev Zoo', 'pageNumber': 53},
  {'title': '83. Peb Yuav Hu Nkauj Qhuas', 'pageNumber': 54},
  {'title': '84. Vim Kuv Paub', 'pageNumber': 54},
  {'title': '85. Tsa Vajtswv Lub Npe', 'pageNumber': 55},
  {'title': '86. Ci Ntsa Iab', 'pageNumber': 55},
  {'title': '87. Peb Vaj Leej Txiv', 'pageNumber': 56},
  {'title': '88. Thov Txhawb Nqa', 'pageNumber': 56},
  {'title': '89. Kuv Tus Tswv Yexus', 'pageNumber': 57},
  {'title': '90. Vaj Leej Txiv Thov Koj Hlub Kuv', 'pageNumber': 58},
  {'title': '91. Qhuas Vajtswv', 'pageNumber': 59},
  {'title': '92. Me Xi Yas', 'pageNumber': 60},
  {'title': '93. Koj Piv Zoo Li Lub Pob Zeb', 'pageNumber': 60},
  {'title': '94. Vaj Tswv Piv Li Lub Pob Zeb', 'pageNumber': 61},
  {'title': '95. Thov Kev Hlub', 'pageNumber': 61},
  {'title': '96. Kuv Paub Tseeb', 'pageNumber': 62},
  {'title': '97. Thaum Vaj Ntsuj Plig Nqis los', 'pageNumber': 62},
  {'title': '98. Txhua Hnub Kuv Yuav Hu Nkauj Qhuas', 'pageNumber': 63},
  {'title': '99. Cia Peb Los Qhuas', 'pageNumber': 64},
  {'title': '100. Koj Dawb Huv', 'pageNumber': 64}
];
